name: Upload Allure Results to S3

on:
  push:
    branches:
      - master  # branch name
  workflow_dispatch: # Allows manual trigger

jobs:
  test-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests & Generate Allure Results
        run: mvn clean verify

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install awscli -y
          aws --version

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}    # AWS access key
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} #AWS secret access key
          aws configure set region us-east-1  # AWS region

      - name: Upload Allure Results to S3
        run: |
          aws s3 cp target/site/allure-maven-plugin s3://allure-report/${{ github.run_id }}/ --recursive