name: Upload Allure Results to S3

on:
  push:
    branches:
      - master  # Runs on push to master
  workflow_dispatch:  # Allows manual trigger

jobs:
  test-and-upload:
    runs-on: windows-latest  # Runs on Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests & Generate Allure Results
        run: mvn clean verify

      - name: Install AWS CLI
        run: |
          Invoke-WebRequest -Uri "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile "AWSCLIV2.msi"
          Start-Process msiexec.exe -ArgumentList "/i AWSCLIV2.msi /quiet /norestart" -Wait
          aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Allure Results to S3
        run: aws s3 sync target\site\allure-maven-plugin s3://allure-report/${{ github.run_id }}/